Oauth
acmbpdc/mouseless pull request #11
Opened 2024-08-19 11:13 UTC by AakarM1

Oauth for google

May have to change/add client id (962811866770-6uourl66lqhb72a61263hnor0jckccgs.apps.googleusercontent.com) and client secret (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). 

TODO After publishing
1. add the final published link to the google oauth page for it to work well.
2. add the final published link to django social part with admin

2024-08-23 15:42 UTC, Fir121 requested changes
All in all awesome work. Had some venv setup issues, fix that up. README updates and make it mandatory google login.

Once done will give a quick review again, resolve each point of the review when you fix it.

2024-08-23 15:42 UTC, Fir121 commented on README.md
> +    git clone https://pypi.org/project/vocabulum/
Put the actual link here

2024-08-23 15:42 UTC, Fir121 commented on README.md
> +    pip install -r requirements.txt
Add directions to make a venv just before this

2024-08-23 15:42 UTC, Fir121 commented on README.md
> -from django.urls import re_path as url
this was not fixed, so don't remove it from the README, we still need to do it

2024-08-23 15:42 UTC, Fir121 commented on requirements.txt
Add in `requests` and `PyJWT` and `django-cors-headers` latest versions. I had an issue when setting up my environment, these were missing.

2024-08-23 15:42 UTC, Fir121 commented on requirements.txt
Add a version number for django-allauth

2024-08-23 15:42 UTC, Fir121 commented on quiz/templates/quiz/login.html
>              {% csrf_token %}
can we not have the default form itself. Only google login allowed, consequently you can remove the sign up page and any link referring to it

2024-08-23 15:42 UTC, Fir121 commented on quiz/templates/quiz/login.html
> +                <img src="https://playtht-website-assets.s3.amazonaws.com/img/brand/google.svg" alt="Google logo"/>Sign in with Google
make it `Log in` with Google

2024-08-24 07:11 UTC, AakarM1 reviewed
All changes made as requested

2024-08-24 07:11 UTC, merged

2024-08-24 15:18 UTC, Fir121 commented
Make an .ENV for the secret and client id. Load that in via python-dotenv

Add these instructions to the README

so this works properly for deployment as well.

2024-08-24 15:19 UTC, Fir121 commented
and when there are a lot of commits, we use squash and merge, it's cleaner

2024-08-24 15:20 UTC, Fir121 commented
once env is setup you can add it with your next PR. Refresh the secret as well since by now it has been accessed by 85% of the world's hacking bots

2024-08-24 16:54 UTC, suryavirkapur commented
```urlpatterns = [
    path('', quiz_views.home, name='home'),
    path('markdownx/', include('markdownx.urls')),
    path('admin/', admin.site.urls),
    # path('register/', quiz_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='quiz/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='quiz/logout.html'), name='logout'),
    path('player/', include('player.urls')),
    path('task/', include('quiz.urls')),

    path('leaderboard/', quiz_views.leaderboard, name='leaderboard'),
    path("accounts/",include('allauth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    path('leaderboard/', quiz_views.leaderboard, name='leaderboard')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)```

- There are some errors. 
- Requirements.txt is missing some new deps.